=== hordiales/ap-gen/examples/AudioPluginDef.dtd
<!ELEMENT AudioPlugin (Metadata, Inputs, Outputs, OutputPlugin)>
		<!ATTLIST AudioPlugin Version CDATA #REQUIRED>

<!ELEMENT Metadata (Name, Description, Authors, Copyright, License, UID?, Category?)>
	<!ELEMENT Name (#PCDATA)>
	<!ELEMENT Description (#PCDATA)>
	<!ELEMENT Authors (#PCDATA)>
	<!ELEMENT Copyright (#PCDATA)>
			<!ATTLIST Copyright Year CDATA #REQUIRED>
	<!ELEMENT License (#PCDATA)>
	<!ELEMENT UID (#PCDATA)> <!-- Unique ID needed for some standards -->
	<!ELEMENT Category (#PCDATA)> <!-- necesaria para CLAM, default: Plugins -->

<!ELEMENT Inputs  (Port*, Control*)>
<!ELEMENT Outputs (Port*, Control*)>
	<!ELEMENT Port (#PCDATA)>
			<!ATTLIST Port Name CDATA #REQUIRED>
	<!ELEMENT Control (#PCDATA)>
			<!ATTLIST Control Name CDATA #REQUIRED>
			<!ATTLIST Control Min CDATA #IMPLIED>
			<!ATTLIST Control Max CDATA #IMPLIED>
			<!ATTLIST Control DefaultValue CDATA #IMPLIED>

<!ELEMENT OutputPlugin (BaseTemplateName, CLAM_DefaultConfig?, VST_DefaultConfig?)>
		<!ATTLIST OutputPlugin Standard (CLAM|VST) #REQUIRED>
		<!ATTLIST OutputPlugin BuildSystem (Scons|Makefile) #REQUIRED>
		<!ATTLIST OutputPlugin OS (Linux|Windows|Mac|Crosscompile) #REQUIRED>
	<!ELEMENT BaseTemplateName (#PCDATA)>

	<!ELEMENT CLAM_DefaultConfig (BaseClass, WithConfig, clam_prefix?)>
		<!ELEMENT BaseClass (#PCDATA)>
		<!ELEMENT WithConfig (#PCDATA)>
		<!ELEMENT clam_prefix (#PCDATA)>

	<!ELEMENT VST_DefaultConfig (WithGUI?, vst_prefix?)>
		<!ELEMENT WithGUI (#PCDATA)>
		<!ELEMENT vst_prefix (#PCDATA)>

=== hordiales/ap-gen/examples/clam-example-plugin-def.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE AudioPlugin SYSTEM "AudioPluginDef.dtd">
<AudioPlugin Version="0.1">
	<Metadata>
		<Name>clamTestRtPlugin</Name>
		<Description>This is a test realtime audio plugin</Description>
		<Authors>Fulano, Sultano, Mengano</Authors>
		<Copyright Year="2010">Club de Audio FIUBA</Copyright>
		<License>GPL</License>
		<!-- <UID>1400</UID> Comment: Unique ID is not needed in clam's plugins -->
		<Category>Plugins</Category>
	</Metadata>

	<!--TODO: Considerar agregar un Realtime=True/False. Para que podrÃ­a servir. Alcanza con que este implicito en el tipo de standard? -->

	<Inputs>
		<Port Name="L Input">AudioInPort</Port>
		<Port Name="R Input">AudioInPort</Port>

		<Control Name="Gain" Min="0." Max="1.0" DefaultValue=".5">FloatInControl</Control>
	</Inputs>
	<Outputs>
		<Port Name="L Output">AudioOutPort</Port>
		<Port Name="R Output">AudioOutPort</Port>
	</Outputs>

	<OutputPlugin Standard="CLAM" BuildSystem="Scons" OS="Linux">
		<BaseTemplateName>Default</BaseTemplateName>

		<CLAM_DefaultConfig> <!--  CLAM plugin specific configuration -->
			<BaseClass>Processing</BaseClass>
			<WithConfig>True</WithConfig>
			<clam_prefix>~/dev/local/clam_dev</clam_prefix> <!-- optional -->
		</CLAM_DefaultConfig>

	<!--VST plugin specific configuration example
		<VST_DefaultConfig> 
			<vst_prefix>~/dev/local/vst_sdk</vst_prefix>
		</VST_DefaultConfig>
	-->
	</OutputPlugin>
</AudioPlugin>

=== hordiales/ap-gen/examples/vst-example-plugin-def.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE AudioPlugin SYSTEM "AudioPluginDef.dtd">
<AudioPlugin Version="0.1">
	<Metadata>
		<Name>vstTestRtPlugin</Name>
		<Description>This is a test realtime audio plugin</Description>
		<Authors>Fulano, Sultano, Mengano</Authors>
		<Copyright Year="2010">Club de Audio FIUBA</Copyright>
		<License>GPL</License>
		<UID>APTestRtPlugin</UID>
		<Category>kPlugCategEffect</Category>  <!-- Simple Effect -->
	</Metadata>

	<Inputs>
		<Port Name="L Input">AudioInPort</Port>
		<Port Name="R Input">AudioInPort</Port>

		<Control Name="Gain" Min="0." Max="1.0" DefaultValue=".5">Float</Control>
	</Inputs>
	<Outputs>
		<Port Name="L Output">AudioOutPort</Port>
		<Port Name="R Output">AudioOutPort</Port>
	</Outputs>

	<OutputPlugin Standard="VST" BuildSystem="Scons" OS="Linux">
		<BaseTemplateName>Default</BaseTemplateName>

		<!--VST plugin specific configuration example -->
			<!--TODO: add Vendor? or take Copyright value? -->
		<VST_DefaultConfig> 
			<vst_prefix>~/dev/local/vst_sdk</vst_prefix>
		</VST_DefaultConfig>

	</OutputPlugin>
</AudioPlugin>

=== hordiales/ap-gen/examples/ladspa-example-plugin-def.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE AudioPlugin SYSTEM "AudioPluginDef.dtd">
<AudioPlugin Version="0.1">
	<Metadata>
		<Name>ladspaTestRtPlugin</Name>
		<Description>This is a test realtime audio plugin</Description>
		<Authors>Fulano, Sultano, Mengano</Authors>
		<Copyright Year="2010">Club de Audio FIUBA</Copyright>
		<License>GPL</License>
		<UID>1400</UID> <!-- LADSPA Unique ID -->

		<!-- <Category>Plugins</Category> -->

	</Metadata>

	<Inputs>
		<Port Name="L Input">AudioInPort</Port>
		<Port Name="R Input">AudioInPort</Port>

		<Control Name="Distortion" Min="0." Max="1.0" DefaultValue=".5">Data</Control>
	</Inputs>
	<Outputs>
		<Port Name="L Output">AudioOutPort</Port>
		<Port Name="R Output">AudioOutPort</Port>
	</Outputs>

	<OutputPlugin Standard="LADSPA" BuildSystem="Makefile" OS="Linux">
		<BaseTemplateName>Default</BaseTemplateName>

		<LADSPA_DefaultConfig> <!--  LADSPA plugin specific configuration -->
		</LADSPA_DefaultConfig>

	</OutputPlugin>
</AudioPlugin>

=== hordiales/ap-gen/examples/vst-c-style-example-plugin-def.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE AudioPlugin SYSTEM "AudioPluginDef.dtd">
<AudioPlugin Version="0.1">
	<Metadata>
		<Name>vst_test_rt_plugin</Name>
		<Description>This is a test plugin</Description>
		<Authors>Fulano, Sultano, Mengano</Authors>
		<Copyright Year="2010">Fulano</Copyright>
		<License>GPL</License>
		<Library>Test</Library>
		<UID>1000</UID>
		<Category>Effect</Category>  <!-- Simple Effect -->
	</Metadata>

	<Inputs>
		<Port Name="input_L">AudioInPort</Port>
		<Port Name="input_R">AudioInPort</Port>

		<Control Name="gain" Min="0." Max="1.0" DefaultValue=".5">Float</Control>
	</Inputs>
	<Outputs>
		<Port Name="output_L">AudioOutPort</Port>
		<Port Name="output_R">AudioOutPort</Port>
	</Outputs>

	<OutputPlugin Standard="VST" BuildSystem="Makefile" OS="Linux">
		<BaseTemplateName>cross_compiled_c_style</BaseTemplateName>

		<!--VST plugin specific configuration example -->
			<!--TODO: add Vendor? or take Copyright value? -->
		<VST_DefaultConfig> 
			<vst_prefix>$(HOME)/dev/audio/vst/vstsdk2.4</vst_prefix>
		</VST_DefaultConfig>

	</OutputPlugin>
</AudioPlugin>

=== hordiales/ap-gen/examples/vstmidi-example-plugin-def.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE AudioPlugin SYSTEM "AudioPluginDef.dtd">
<AudioPlugin Version="0.1">
	<Metadata>
		<Name>vstMIDITestPlugin</Name>
		<Description>This is a test plugin</Description>
		<Authors>Fulano, Sultano, Mengano</Authors>
		<Copyright Year="2010">Club de Audio FIUBA</Copyright>
		<License>GPL</License>
		<Library>Test</Library>
		<UID>1000</UID>
		<Category>Effect</Category>
	</Metadata>

	<Inputs>
		<Port Name="L Input">AudioInPort</Port>
		<Port Name="R Input">AudioInPort</Port>

		<Control Name="Gain" Min="0." Max="1.0" DefaultValue=".5">Float</Control>
	</Inputs>
	<Outputs>
		<Port Name="L Output">AudioOutPort</Port>
		<Port Name="R Output">AudioOutPort</Port>
	</Outputs>

	<OutputPlugin Standard="VST" BuildSystem="Makefile" OS="Linux">
		<BaseTemplateName>CrossCompiledMIDI</BaseTemplateName>

		<!--VST plugin specific configuration example -->
		<VST_DefaultConfig> 
			<vst_prefix>$(HOME)/dev/audio/vst/vstsdk2.4</vst_prefix>
		</VST_DefaultConfig>
	</OutputPlugin>
</AudioPlugin>

=== hordiales/ap-gen/examples/vst-w64-example-plugin-def.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE AudioPlugin SYSTEM "AudioPluginDef.dtd">
<AudioPlugin Version="0.1">
	<Metadata>
		<Name>vst_w64_TestRtPlugin</Name>
		<Description>This is a test plugin</Description>
		<Authors>hordia</Authors>
		<Copyright Year="2017">hordia</Copyright>
		<License>GPL</License>
		<Library>Test</Library>
		<UID>1000</UID>
		<Category>Effect</Category>  <!-- Simple Effect -->
	</Metadata>

	<Inputs>
		<Port Name="L Input">AudioInPort</Port>
		<Port Name="R Input">AudioInPort</Port>

		<Control Name="Gain" Min="0." Max="1.0" DefaultValue=".5">Float</Control>
	</Inputs>
	<Outputs>
		<Port Name="L Output">AudioOutPort</Port>
		<Port Name="R Output">AudioOutPort</Port>
	</Outputs>

	<OutputPlugin Standard="VST" BuildSystem="Makefile" OS="Linux">
		<BaseTemplateName>CrossCompiled_w64</BaseTemplateName>

		<!--VST plugin specific configuration example -->
			<!--TODO: add Vendor? or take Copyright value? -->
		<VST_DefaultConfig> 
			<vst_prefix>$(HOME)/dev/audio/vst/vstsdk2.4</vst_prefix>
		</VST_DefaultConfig>

	</OutputPlugin>
</AudioPlugin>
